package com.fdpsm.exercise.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.fdpsm.exercise.dao.MovieQuery;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOVIE_QUERY".
*/
public class MovieQueryDao extends AbstractDao<MovieQuery, Long> {

    public static final String TABLENAME = "MOVIE_QUERY";

    /**
     * Properties of entity MovieQuery.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SearchText = new Property(1, String.class, "searchText", false, "SEARCH_TEXT");
        public final static Property SearchDate = new Property(2, java.util.Date.class, "searchDate", false, "SEARCH_DATE");
    };

    private DaoSession daoSession;


    public MovieQueryDao(DaoConfig config) {
        super(config);
    }
    
    public MovieQueryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOVIE_QUERY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SEARCH_TEXT\" TEXT NOT NULL ," + // 1: searchText
                "\"SEARCH_DATE\" INTEGER NOT NULL );"); // 2: searchDate
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_MOVIE_QUERY_SEARCH_TEXT ON MOVIE_QUERY" +
                " (\"SEARCH_TEXT\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOVIE_QUERY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MovieQuery entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSearchText());
        stmt.bindLong(3, entity.getSearchDate().getTime());
    }

    @Override
    protected void attachEntity(MovieQuery entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MovieQuery readEntity(Cursor cursor, int offset) {
        MovieQuery entity = new MovieQuery( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // searchText
            new java.util.Date(cursor.getLong(offset + 2)) // searchDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MovieQuery entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSearchText(cursor.getString(offset + 1));
        entity.setSearchDate(new java.util.Date(cursor.getLong(offset + 2)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MovieQuery entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MovieQuery entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
