package com.fdpsm.exercise.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MOVIE_DETAIL".
 */
public class MovieDetail {

    private Long id;
    /** Not-null value. */
    private String title;
    private String releaseDate;
    private String runtime;
    private String posterUrl;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MovieDetail() {
    }

    public MovieDetail(Long id) {
        this.id = id;
    }

    public MovieDetail(Long id, String title, String releaseDate, String runtime, String posterUrl) {
        this.id = id;
        this.title = title;
        this.releaseDate = releaseDate;
        this.runtime = runtime;
        this.posterUrl = posterUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

    public String getRuntime() {
        return runtime;
    }

    public void setRuntime(String runtime) {
        this.runtime = runtime;
    }

    public String getPosterUrl() {
        return posterUrl;
    }

    public void setPosterUrl(String posterUrl) {
        this.posterUrl = posterUrl;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
